name: Lint and Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  GOPRIVATE: "github.com/Invisv-Privacy/*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        working-directory: ./
        args: --timeout 5m

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Test
      run: go test -v ./...

